[package]
name = "player"
publish = false
version.workspace = true
edition.workspace = true

[dependencies]
cpal = "0.15.2"
tokio = { version = "1.28.1", features = ["macros", "net", "rt-multi-thread", "io-util", "sync", "time"] }
tokio-util = { version = "0.7.8", features = ["codec"] }
protocol = { path = "../protocol" }
futures = "0.3.28"
bincode = "1.3.3"
bytes = "1.4.0"
