[package]
name = "server"
publish = false
version.workspace = true
edition.workspace = true

[dependencies]
bincode = "1.3.3"
futures = "0.3.28"
protocol = { path = "../protocol" }
tokio = { version = "1.28.1", features = ["macros", "net", "rt-multi-thread", "io-util", "sync"] }
